{
 "title": "Balancer Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service Latency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(balancer_service_latency_bucket[$__rate_interval])) by (service, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balancer Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(balancer_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Alive",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "balancer_service_alive", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Balancer RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(balancer_requests[$__interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Backend RPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "rate(balancer_service_requests[$__interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Balancer Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(balancer_errors[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balancer RPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "rate(balancer_requests[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend Alive",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "balancer_service_alive", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Backend RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(balancer_service_requests[$__interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "{service_name=\"unknown_service\"} |= ``"
    }
   ]
  }
 ]
}